/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Error: typeof import('./src/components/Error.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
  }
}
